-- Down for 060. No dependency order needed — the five tables are unrelated to
-- each other and nothing references them.
--
-- Destructive: trending_entities is regenerated by the cron within two hours,
-- but user_connections, story_completions, subscription_meals and
-- rider_locations hold real user data once live.

DROP TABLE IF EXISTS rider_locations;
DROP TABLE IF EXISTS subscription_meals;
DROP TABLE IF EXISTS story_completions;
DROP TABLE IF EXISTS user_connections;
DROP TABLE IF EXISTS trending_entities;
